x-app: &default-app
  image: ontoportal_web_ui
  build:
    context: .
    args:
      RUBY_VERSION: '2.7.8'
      RAILS_ENV: 'development'
  env_file:
    - ".env"
  tty: true
  volumes:
    - .:/app
    - bundle:/usr/local/bundle
    - node:/node_modules
    - rails_cache:/app/tmp/cache
    - assets:/app/public/assets
    - /var/run/docker.sock:/var/run/docker.sock
  tmpfs:
    - /tmp
    - /app/tmp/pids

services:
  db:
    image: "mysql:8.0"
    networks:
      - default
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

  cache:
    image: memcached:latest
    restart: unless-stopped
    command: [ "-m", "1024" ]
    networks:
      - default
    ports:
      - "11211:11211"
  node:
    <<: *default-app
    command: "yarn build --watch"
    tty: true
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node:/node_modules
      - rails_cache:/app/tmp/cache
      - assets:/app/public/assets
      - /var/run/docker.sock:/var/run/docker.sock

  rails:
    <<: *default-app
    depends_on:
      - db
      - cache
      - node
    links:
      - db
      - cache
    environment:
      BUNDLE_WITHOUT: ''
      DB_HOST: db
      CACHE_HOST: cache
    ports:
      - "3000:3000"
  test:
    <<: *default-app
    depends_on:
      - db
      - cache
    network_mode: 'host'
    environment:
      BUNDLE_WITHOUT: ''
      DB_HOST: 127.0.0.1
      CACHE_HOST: 127.0.0.1


volumes:
  mysql-data:
  bundle:
  rails_cache:
  assets:
  node:
